/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

public class ASTIdentifier extends SimpleNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  // PLB
  private String value = null;
  public void setValue(String v) { value = v; }
  public String getValue() { return value; }

  private String estMort = null;
  public void setMort(String v) { estMort = v; }
  public String getMort() { return estMort; }
}
